Repository OneIdea-IRNITU/it_academy_web, pull requests merged in 2021-06, with the labels that each got.

#35 Сортировка по актуальности
  src/views/EventList.vue
Labels: enhancement

#36 Release Сортировка по актуальности
  src/views/EventList.vue
Labels: release

#37 Перенаправление кнопкой Назад на publicPath
  src/views/EventCard.vue
Labels: bug-fix

#38 Release Перенаправление кнопкой Назад на publicPath
  src/views/EventCard.vue
Labels: bug-fix, release

#39 Добавить согласие на обработку ПД в форму регистрации
  src/components/ConsentToPersonalData.vue
  src/components/EventRegistrationForm.vue
Labels: enhancement

#40 Release Согласие на обработку ПД
  src/components/ConsentToPersonalData.vue
  src/components/EventRegistrationForm.vue
Labels: enhancement, release

#42 Добавить поиск по названию и организаторам
  src/views/EventList.vue
Labels: enhancement

#43 Release Поиск по названию и организаторам
  src/views/EventList.vue
Labels: enhancement, release

#44 Поиск по организатору из карточки
  src/router.js
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement

#45 Release Поиск по организатору из карточки
  src/router.js
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement, release

#47 Изменить router mode на history
  src/router.js
Labels: bug-fix

#48 Release Изменить router mode на history
  src/router.js
Labels: bug-fix, release

#49 Сделать таймер отслеживания времени до мероприятий.
  package-lock.json
  src/App.vue
  src/components/EventRegistrationForm.vue
  src/components/Timer.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement

#50 timer in the announcement of the event
  src/components/Timer.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement, refactoring

#51 Адаптивная верстка
  public/index.html
  src/App.vue
  src/assets/NavBar/login_icon.svg
  src/assets/NavBar/search_icon.svg
  src/assets/calendar_icon.svg
  src/assets/timer_icon.svg
  src/components/EventRegistrationForm.vue
  src/components/Footer.vue
  src/components/NavBar.vue
  src/components/Timer.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement

#52 Release Таймер и адаптивная верстка
  package-lock.json
  public/index.html
  src/App.vue
  src/assets/NavBar/login_icon.svg
  src/assets/NavBar/search_icon.svg
  src/assets/calendar_icon.svg
  src/assets/timer_icon.svg
  src/components/EventRegistrationForm.vue
  src/components/Footer.vue
  src/components/NavBar.vue
  src/components/Timer.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement, release

#60 Правки по верстке от 09.06.2021
  src/App.vue
  src/assets/back_btn_icon.svg
  src/components/EventRegistrationForm.vue
  src/components/NavBar.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement, refactoring

#61 Release Правки по верстке от 09.06.2021
  src/App.vue
  src/assets/back_btn_icon.svg
  src/components/EventRegistrationForm.vue
  src/components/NavBar.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement, refactoring, release

#64 Правки по верстке
  public/favicon.ico
  public/index.html
  src/App.vue
  src/components/Footer.vue
  src/components/NavBar.vue
  src/router.js
  src/views/EventList.vue
Labels: enhancement, refactoring

#65 Release Правки по верстке
  public/favicon.ico
  public/index.html
  src/App.vue
  src/components/Footer.vue
  src/components/NavBar.vue
  src/router.js
  src/views/EventList.vue
Labels: enhancement, refactoring, release

#66 Auto deploy
  .github/workflows/deploy.yaml
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: enhancement

#67 Release Auto deploy
  .github/workflows/deploy.yaml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement, release

#68 Добавить GITHUB_TOKEN
  .github/workflows/deploy.yaml
  .github/workflows/node.js.yml
  .travis.yml
Labels: bug-fix

#69 Release Добавить GITHUB_TOKEN
  .github/workflows/deploy.yaml
  .github/workflows/node.js.yml
  .travis.yml
Labels: bug-fix, release

#72 Добавить авторов в список мероприятий
  src/assets/organizer_icon.svg
  src/views/EventList.vue
Labels: enhancement

#73 Блокировка кнопки подачи заявки в карточке завершенного мероприятия
  src/components/EventRegistrationForm.vue
  src/views/EventCard.vue
Labels: enhancement

#74 Фикс кнопки "Регистрация окончена"
  src/components/EventRegistrationForm.vue
Labels: bug-fix

#75 Заменить удаление последних символов во времени на замену символов
  src/views/EventCard.vue
Labels: bug-fix

#77 Пофиксить баг с повторным выводом таймера и даты в ивент листе
  src/views/EventList.vue
Labels: bug-fix

#78 Таймер, организаторы на главный экран, уведомление ...
  src/assets/organizer_icon.svg
  src/components/EventRegistrationForm.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement

#83 Вёрстка окна уведомления.
  package-lock.json
  package.json
  src/App.vue
  src/components/EventRegistrationForm.vue
Labels: enhancement

#86 Features/router mode
  package-lock.json
  src/router.js
Labels: enhancement

#87 Release Изменить router mode
  package-lock.json
  src/router.js
Labels: enhancement

#88 Использовать vuex для фильтра и поиска
  package-lock.json
  package.json
  src/main.js
  src/store.js
  src/views/EventList.vue
Labels: enhancement

#89 Release Использовать vuex для фильтра и поиска
  package-lock.json
  package.json
  src/main.js
  src/store.js
  src/views/EventList.vue
Labels: enhancement

#90 Добавить поиск по категориям
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement

#91 Release Добавить поиск по категориям
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement

#92 Правки по верстке
  src/App.vue
  src/components/EventRegistrationForm.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: enhancement

#93 Release Правки по верстке
  src/App.vue
  src/components/EventRegistrationForm.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: bug-fix, enhancement, refactoring, release

#94 Исправить отступы формы регистрации на мобилках
  src/components/EventRegistrationForm.vue
Labels: bug-fix

#95 Release Исправить отступы формы регистрации на мобилках
  src/components/EventRegistrationForm.vue
Labels: bug-fix, release

#99 Fix/issues 81 96 98
  src/components/NavBar.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: bug-fix, enhancement

#100 Фикс пробелов в списке организаторов, заменить Loading на Загрузка, добавить ссылку на личный кабинет
  src/components/NavBar.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: bug-fix, enhancement

#102 Исправить баги и сделать рефакторинг.
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/components/EventRegistrationForm.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: bug, refactoring

#103 Исправить баги и сделать рефакторинг.
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/components/EventRegistrationForm.vue
  src/views/EventCard.vue
  src/views/EventList.vue
Labels: bug-fix

#104 Подогнать форму регистрации под фигму
  src/components/EventRegistrationForm.vue
Labels: refactoring

#105 Подогнать форму регистрации под фигму
  src/components/EventRegistrationForm.vue
Labels: refactoring
